### ISSUE TITLE
Add `is_sparse_tibble()`

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/sparsevctrs#70]
The gist could happen with the following R code, but it doesn't have an early return. which might slow us down on wide data.frames

```r
is_sparse_tibble <- function(x) {
  any(vapply(x, sparsevctrs::is_sparse_vector, logical(1)))
}
```

**Comment by simonpcouch** [comment]
Just came here to file an issue about this: +1!

**Comment by simonpcouch** [comment]
It may also be nice to clarify in the `coerce_to_sparse_tibble()` (and this new function's documentation) that a user will not be able to tell from printing or `class(x)` that `x` is a sparse vs dense tibble.

**Comment by EmilHvitfeldt** [comment]
has been noted elsewhere. This doesn't actually test that the object is a tibble. so it should be renamed. Maybe `has_sparse_elements/columns/cols()`
